### PR TITLE
Master - Selenium TimeAccounting remaining tests

### PR DESCRIPTION
**Pull request by s7design**
Hi @carlosfrodriguez ,

Here are remaining selenium test for Agent and Output modules. AgentTimeAccountingEdit.t test is modified to include new modernized fields for. It will work with those changes (https://github.com/OTRS/TimeAccounting/pull/8). 
If this is inconvenient for you, could split that test in separate PR for easier review.

Regards,
Sanjin

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Sanjin

Thank you for you pull request I have an error in AgentTimeAccountingEdit test

 not ok 80 - Exception in Selenium': An element could not be located on the page using the given search parameters: #IncompleteWorkingDaysList,css selector at (eval 97) line 151.

It could be due to the resent changes in the screen, please rebase this PR and make sure to set all needed settings to its default (so it can work on any environment)

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

You are right, there was issue in AgentTimeAccountingEdit.
I rebesed this PR and tested all tests. They work now on my system.
Please let me know if there are wrong test results.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Zoran,

I Still have the same issue, could it be that there is something missing in my system (a PR that I haven't merged?) I can't find any html element with id IncompleteWorkingDaysList in my screen.

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez,

I updated the test for  AgentTimeAccountingEdit. It worked on my local system. I have just tested it on fresh vanilla OTRS framework with TA from this PR, installed on this system. 

All test worked fine with the previous version as well:
<pre>
perl bin/otrs.Console.pl Dev::UnitTest::Run --test AgentTimeAccountingEdit:AgentTimeAccountingOverview:AgentTimeAccountingReporting:AgentTimeAccountingSetting:AgentTimeAccountingView
</pre>
screen shot 2015-08-11 at 3 32 59 pm


Maybe there could be a problem
* if there are no days without entries
* or if TimeAccounting::AllowMassEntryForUser is enabled
In these cases there is not IncompleteWorkingDaysList on the screen.

I think that it is better if we omit checking this select box. 
Please let me know, are still there issues  with the update version of test.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Zoran,

Another possibility is to set the sysconfig options as needed for the test environment ;-)

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

Thanks, I updated PR. I added disable 'AllowMassEntryForUser' sysconfig item. I am not sure if it will solve issue here. It works fine on my local system in any cases.
I did not disable this item at first, because it is disabled by default in vanilla system.

Please let me know what is result of testing now. If you have idea what is the problem please give me feedback. 

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Zoran,

I merge this pull request in https://github.com/OTRS/TimeAccounting/commit/6431ad6a593043415854d86e7991a2e8968ba3f9.

Still with the changes I was not able to execute the Edit test successfully, I realize that the setting name was wrong, I fix it and also fix some code style issues and some typos.

((enjoy))
cr

**Pull request closed without merging**
