### PR TITLE
Master - TA updated GetStatTablePreview function

### PR DESCRIPTION
**Pull request by s7design**
Hi @carlosfrodriguez 

As you suggested when we planned tasks for TimeAccounting modules, I redefined  GetStatTablePreview function. It generates dummy data now instead of using real ones.

P.S. I called new function  Translate() for attributes of statistic, as it is being used in the framework.
Working on this task I saw an issue. I will open new PR with fix for this in the framework.

Regards
Zoran

### CODE REVIEW

**Comment by s7design** [comment]
Hi,

There is fix of the issues which I mentioned in the previous comment https://github.com/OTRS/otrs/pull/673

With this fix you will be able to test  GetStatTablePreview() function and of course the result of statistic will be as we set in the stats settings. 

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Zoran

I got an uninitialized variable error in  line 457
```perl
if ( $Param{ValueSeries} && $Param{ValueSeries}[0]{SelectedValues}[0] eq 'Down' ) {
```
When I was defining a new report. 

I think we can change it to something like:
```perl
if (
            IsArrayRefWithData( $Param{ValueSeries} )
            && IsArrayRefWithData( $Param{ValueSeries}[0]{SelectedValues} )
            && $Param{ValueSeries}[0]{SelectedValues}[0] eq 'Down'
            )
        {
            @SortedUserIDs = reverse @SortedUserIDs;
        }
```
But I haven't test it, (don't gorget the <b>use</b> pragma to the =VariableCheck=)

Now regarding the 
```
Translatable('...')
```

I think this are only markers so the create translation scripts can parse the .pm and gather this strings and puts into the translation files, but it does not translate the string itself (but I could be wrong) please review it.

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

You are right. It is better to use VariableCheck function here. I updated PR. It is tested; and it works fine.

Regarding the Translatable('...'), you are also right. It  is a no-op to mark a text as translatable in the Perl code, as it is said in POD of the function. I saw it in the other modules for statistics (TicketList, TicketAccountedTime ... ), because of that I have used it here. I suppose it will be necessary to use it in the further work and maybe update the framework where it is needed.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

 This pull request was merged in https://github.com/OTRS/TimeAccounting/commit/36197b359f5160e0c4f2eeea479dcb63ca069a03, I made some code style fixes in general.

((enjoy))
cr

**Pull request closed without merging**
