### PR TITLE
Added possibility to translate the documentation, Hungarian translation

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @mgruner 
This PR makes it possible to translate the documentation of this module. I also send the initial Hungarian translation, and small fixes for the documentation.
It would be good, it the next release would contain the generated (.pdf) version of the Hungarian doc.

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @mgruner 
Can you check this PR? Unfortunately 5.0.2 is released, so it might be the part of 5.0.3...

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez and @mgruner 
Can you check this PR? Is it possible, that the next version of this package can contain Hungarian documentation?

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez  and @mgruner 
Can you check this pull request?

**Comment by carlosfrodriguez** [comment]
Hi @urbalazs,

Thank you for your pull request,

The fixes where added in https://github.com/OTRS/TimeAccounting/commit/b04d095f384a95f65cb14c6738bc96dc64da8c46

About the translation, I need to discuss with @mgruner the best approach to do it.

((enjoy))
cr

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez and @mgruner 
Could you discuss, what would be the best place for the Hungarian translation of the documentation?

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez and @mgruner 
Any news?

**Comment by mgruner** [comment]
Hello @urbalazs, @carlosfrodriguez. We decided not to include the translations at this point, this would require changes to our infrastructure that we currently don't have resources for (it would affect all public packages). Maybe we can revisit the issue in some time. Thanks a lot though for your contribution, @urbalazs!

**Pull request closed without merging**
